---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
 name: podid
spec:
 type: 0
 ResourceID: /subscriptions/<subscriptionId>/resourcegroups/<resource group>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<managed identity name>
