# This file contains the essential configs for the ingress controller helm chart

################################################################################
# Specify which application gateway the ingress controller will manage
#
appgw:
    subscriptionId: <subscription id>
    resourceGroup: <resource group>
    name: bootcamp2019

################################################################################
# Specify which kubernetes namespace the ingress controller will watch
# Default value is "default"
#
# kubernetes:
#   watchNamespace: <namespace>

################################################################################
# Specify the authentication with Azure Resource Manager
#
# Two authentication methods are available:
# - Option 1: AAD-Pod-Identity (https://github.com/Azure/aad-pod-identity)
# - Option 2: ServicePrincipal as a kubernetes secret
# armAuth:
#   type: servicePrincipal
#   secretName: networking-appgw-k8s-azure-service-principal
#   secretKey: ServicePrincipal.json
armAuth:
    type: aadPodIdentity
    identityResourceID: /subscriptions/<subscription id>/resourcegroups/<resource group>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<managed identity name>
    identityClientID: <client id>

rbac:
    enabled: true

aksClusterConfiguration:
    apiServerAddress: <api server DNS>.hcp.westeurope.azmk8s.io